
SELECT H.HACKER_ID, H.NAME, COUNT(CHALLENGE_ID) AS CHALLENGES_CREATED
FROM HACKERS H, CHALLENGES C
WHERE H.HACKER_ID = C.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING CHALLENGES_CREATED IN 
        (SELECT T.CNT
        FROM
            (SELECT HACKER_ID, COUNT(CHALLENGE_ID) CNT
            FROM CHALLENGES 
            GROUP BY HACKER_ID) T
        GROUP BY T.CNT
        HAVING COUNT(T.HACKER_ID) = 1)
        OR
        CHALLENGES_CREATED = 
        (SELECT MAX(CNT)
        FROM
        (SELECT HACKER_ID, COUNT(CHALLENGE_ID) CNT
            FROM CHALLENGES 
            GROUP BY HACKER_ID) T)
ORDER BY 3 DESC, 1 ASC
